name: churn
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.26.*
  - pandas>=2.0,<3.0
  - scipy
  - scikit-learn=1.4.*
  - pyarrow=14.*
  - streamlit>=1.30,<2.0
  - joblib>=1.3,<2.0
  - pip
  - pip:
      - tensorflow>=2.15,<2.18
